"""
MetaWriter 
Author: Shaikh Aquib

This class uses the data generated by MetaReader object and exports it into the form of txt, json, html, pdf.

Param: data (String, Dictionary)  
       (pass the generated data from MetaReader object)

Functions: write_to_html  - Writes data as an HTML file
           write_to_json  - Writes as a json file

"""

import os
import json
from PyPDF2 import PdfFileWriter

class MetaWriter:

    # Constructor taking String or Dictionary data
    def __init__(self, data):
        self.data = data

    # Write the data as an HTML file
    def write_to_html(self, filename):
        with open(filename,"w") as f:
            f.write(self.data)
        f.close()

    # Write the data as a JSON file
    def write_to_json(self, filename):
        with open(filename,"w") as f:
            f.write(json.dumps(self.data))
        f.close()


