import os
import json
from PyPDF2 import PdfFileWriter

class MetaWriter:
    #COPYRIGHT(C) SHAIKH AQUIB
    """
        META WRITER CLASS

This class uses the data generated by MetaReader object and exports it into the form of txt, json, html, pdf.

Param: data (String, Dictionary)\n  <pass the generated data from MetaReader object>

Functions: __init__         - Constructor

    """

    def __init__(self, data):
        self.data = data

    # Write the data as an HTML file
    def write_to_html(self, filename):
        with open(filename,"w") as f:
            f.write(self.data)
        f.close()

    # Write the data as a JSON file
    def write_to_json(self, filename):
        with open(filename,"w") as f:
            f.write(json.dumps(self.data))
        f.close()


